export const CATEGORIES = [
  "Seminar",
  "Workshop",
  "Kompetisi",
  "Webinar",
  "Konser",
  "Olahraga",
];

export const INTEREST_OPTIONS = [
  { label: "Teknologi", emoji: "💻" },
  { label: "Musik", emoji: "🎵" },
  { label: "Olahraga", emoji: "⚽" },
  { label: "Seni", emoji: "🎨" },
  { label: "Bisnis", emoji: "💼" },
  { label: "Debat", emoji: "🗣️" },
  { label: "Fotografi", emoji: "📸" },
  { label: "Gaming", emoji: "🎮" },
  { label: "Menulis", emoji: "✍️" },
  { label: "Film", emoji: "🎬" },
  { label: "Sosial", emoji: "🤝" },
  { label: "Keagamaan", emoji: "🕌" },
];

export const MAJORS = [
  "Agribisnis",
  "Agroteknologi",
  "Akuntansi",
  "Farmasi",
  "Hubungan Internasional",
  "Ilmu Gizi",
  "Ilmu Hukum",
  "Ilmu Keolahragaan",
  "Ilmu Komunikasi",
  "Ilmu Pemerintahan",
  "Informatika",
  "Kebidanan",
  "Manajemen",
  "Manajemen Pendidikan Islam",
  "Pendidikan Agama Islam",
  "Pendidikan Bahasa & Sastra Indonesia",
  "Pendidikan Bahasa Inggris",
  "Pendidikan Islam Anak Usia Dini",
  "Pendidikan Jasmani, Kesehatan & Rekreasi",
  "Pendidikan Luar Sekolah",
  "Pendidikan Matematika",
  "Sistem Informasi",
  "Teknik Elektro",
  "Teknik Industri",
  "Teknik Kimia",
  "Teknik Lingkungan",
  "Teknik Mesin",
];
