export const CATEGORIES = [
  "Seminar",
  "Workshop",
  "Kompetisi",
  "Hiburan",
  "Festival",
  "Oprec",
  "Lainnya",
];

export const MAJORS = [
  "Administrasi Rumah Sakit",
  "Agroteknologi",
  "Agribisnis",
  "Akuntansi",
  "Arsitektur",
  "Farmasi",
  "Fisika",
  "Gizi",
  "Hubungan Internasional",
  "Ilmu Hukum",
  "Ilmu Keolahragaan",
  "Ilmu Komunikasi",
  "Ilmu Pemerintahan",
  "Informatika",
  "Kebidanan",
  "Kimia",
  "Manajemen",
  "Manajemen Pendidikan Islam",
  "Pendidikan Agama Islam",
  "Pendidikan Bahasa dan Sastra Indonesia",
  "Pendidikan Bahasa Inggris",
  "Pendidikan Islam Anak Usia Dini",
  "Pendidikan Jasmani Kesehatan dan Rekreasi",
  "Pendidikan Luar Sekolah",
  "Pendidikan Masyarakat",
  "Pendidikan Matematika",
  "Sistem Informasi",
  "Statistika",
  "Teknologi Industri Pertanian",
  "Teknik Elektro",
  "Teknik Industri",
  "Teknik Informatika",
  "Teknik Kimia",
  "Teknik Lingkungan",
  "Teknik Mesin",
  "Teknik Sipil",
];
